### ISSUE TITLE
Array with shape error when processing mulitbeam data 

### ISSUE THREAD

**Issue by Phoebe-AA** [noaa-ocs-hydrography/kluster#111]
Hello,
I have been practising importing em122 files (.all), and it was going well. So I decided to import and process a larger batch (approximately 28 files) and then kept getting this error: 

C:\... \anaconda3\envs\kluster_test\lib\site-packages\zarr\util.py", line 526, in check_array_shape
    raise ValueError('parameter {!r}: expected array with shape {!r}, got {!r}'
ValueError: parameter 'value': expected array with shape (7530,), got (7752,)

2023-10-02 16:42:26,818 - INFO - kluster_action: no data returned from action execution

Any ideas? Many thanks! 
PS the software is super cool :)

**Comment by ericgyounkin** [comment]
Wondering if it might be related to a specific file.  Would you be able to try smaller batches to see if you can isolate the file?

**Comment by Phoebe-AA** [comment]
I wondered the same, so I started a new project (which of course it reloaded all the same files), but this time it seemed to work. Maybe just a glitch in Python/anaconda...

**Comment by Phoebe-AA** [comment]
Hello again, 
I've been running into this error a lot now:

IndexError: index -1 is out of bounds for axis 0 with size 0

2023-10-03 16:53:46,024 - INFO - kluster_action: no data returned from action execution
Spanning more than one UTM zone: MIN 27, MAX 28

Any ideas on how to fix it? Or to remove from the action list as it wont let me delete it until it has been processed. As I've been working in the same project it only reloads with the same starting point. 
Many thanks

**Comment by ericgyounkin** [comment]
Would you be able to upload some screenshots, just to get a sense of your project?  And which action we are talking about?

**Comment by Phoebe-AA** [comment]
Sorry - after lots of trying yesterday and getting the same messages over and over again - I tried this morning and it worked fine...
