### ISSUE TITLE
EM124 Data Processing in Kluster

### ISSUE THREAD

**Issue by tzutingchen** [noaa-ocs-hydrography/kluster#112]
"Sonar model not understood" issue with the "em124" data

**Comment by ericgyounkin** [comment]
I believe this is as simple as adding an em124 entry to the `sonar_translator` at https://github.com/noaa-ocs-hydrography/kluster/blob/master/HSTB/kluster/xarray_conversion.py#L28, mirroring the existing em122 entry.  

We'd probably need a sample file to ensure that is the case.

@barry-gallagher interested?

**Comment by ericgyounkin** [comment]
See also https://kluster.readthedocs.io/en/latest/for_developers/fordev_sonar.html

**Comment by barry-gallagher** [comment]
This is possible to add but we have a fair backlog on other projects so I won't promise when we'll get to it.  Probably this and #113 would get done at the same time.

**Comment by tzutingchen** [comment]
Thank you for your response. Looking forward to the updates.

**Comment by ericgyounkin** [comment]
@tzutingchen I have this working locally, I'll need to combine with the other sonar support requests and include in a new version.  I'll report back here when that is done.

**Comment by ericgyounkin** [comment]
@tzutingchen This is fixed with v1.1.6.  You should be able to reinstall and get the update.
