### ISSUE TITLE
Processing error

### ISSUE THREAD

**Issue by monocilindro** [noaa-ocs-hydrography/kluster#22]
I am not able to process any multibeam file. The software was installed following carefully the provided instructions and the data could be imported without any problem but it fails to process. I have tried on 2 different machines (Windows) and using multiple Kongsberg .all files (from EM2040, EM3002, EM302, and  EM122).  See the attached log for more details

[log.txt](https://github.com/noaa-ocs-hydrography/kluster/files/5487593/log.txt)

**Comment by ericgyounkin** [comment]
Hi @monocilindro, sorry you are having troubles.  It can't seem to find the network attitude/velocity datagram from the .all file, which is odd.  Would you happen to have an example .all file that you could attach to this ticket?  Or another way of sharing a file?  I believe you can attach a file that is less than 25 MB.

Please let me know.

**Comment by ericgyounkin** [comment]
One other step we could take would be to examine one of these files using the par module.  You should be able to run this after installing kluster.  I would be interested to see if there are 'Network Attitude 110' packets in one of these files.

See the code below:

```
from HSTB.drivers import par3
ad = par3.AllRead(r"C:\data_dir\0015_20200304_070725_S250.all")
ad.mapfile()

Mapping file; finished mapping file.

ad.map.printmap()

PU ID Output 48 (0x30) has 246 packets and is 0.01% of file.
PU Status 49 (0x31) has 244 packets and is 0.01% of file.
Serial Attitude 65 (0x41) has 242 packets and is 0.17% of file.
Clock 67 (0x43) has 244 packets and is 0.00% of file.
Surface Sound Speed 71 (0x47) has 24 packets and is 0.01% of file.
Start Parameters 73 (0x49) has 1 packets and is 0.00% of file.
New Rangle/Angle 78 (0x4e) has 7039 packets and is 25.67% of file.
Position 80 (0x50) has 489 packets and is 0.03% of file.
Runtime Parameters 82 (0x52) has 12 packets and is 0.00% of file.
Sound Speed Profile 85 (0x55) has 1 packets and is 0.00% of file.
New Depth 88 (0x58) has 7039 packets and is 31.95% of file.
New Seabead Imagry 89 (0x59) has 7039 packets and is 40.02% of file.
Stop Parameters 105 (0x69) has 2 packets and is 0.00% of file.
Network Attitude 110 (0x6e) has 2442 packets and is 2.07% of file.
Total size of all packets: 177052176
Total file size 177151320
Percentage of total packet size vs total file size: 99.9440%
```

**Comment by ericgyounkin** [comment]
Resolved these issues in 28f21bf04c973983d10318306c28ebd7d0f70ff4

The Par module Data110 errors were related the the seapath datagram.  The header identifier was not the expected value.  I've included the header found in this file in the par module code (since the data appeared to be of the same format) but further investigation with Kongsberg is probably a good idea.  Ive sent them an email.  Will close the loop when i hear back.

**Comment by ericgyounkin** [comment]
updated par3 to match the seatex data definition document I received from Kongsberg.  You can now see altitude on conversion using the Seapath Version 23/26 formats.  See HSTB Drivers commit 9faf7d7

**Comment by ericgyounkin** [comment]
Updated the kongsberg reader to now support the older rangeangle datagram.  This should allow you to convert the MALASPINA line using Kluster.  I've tested it and it compares with the Caris answer.  Please let me know if you have any other issues, I'll close this issue for now.
