### ISSUE TITLE
Shoalest surface is broken

### ISSUE THREAD

**Issue by giumas** [noaa-ocs-hydrography/kluster#48]
Using the test .all, I got:

![python_Zk0trkSdfp](https://user-images.githubusercontent.com/2849257/129788916-b5a2e3f9-22b8-4197-8d82-f759d99fa903.png)

The mean surface works.

**Comment by monocilindro** [comment]
I am getting the same error using a kmall file (EM2040). No issues when generating the mean depth surface, though

**Comment by ericgyounkin** [comment]
I can replicate this on my end.  It's in the bathygrid module where I go to create a new_grid.  I did not include the layers correctly for the shoalest algorithm.  I will fix this for Kluster 0.7.5 and report back here.

Thanks for the report.

**Comment by ericgyounkin** [comment]
Fixed in Kluster 0.7.5.  Please let me know if you still see the issue.

**Comment by giumas** [comment]
I confirm that, after having pulled from 'main' for both kluster and bathygrid works:

![python_bU5mzW1u1G](https://user-images.githubusercontent.com/2849257/130331751-93e45664-1f4a-44b7-a222-bc66414d0769.png)
