### ISSUE TITLE
Drag & Drop in the '2d View' should add a new data file

### ISSUE THREAD

**Issue by giumas** [noaa-ocs-hydrography/kluster#51]
This is NOT a bug, but a suggested improvement. 

Similarly to other GIS apps, the drag & drop of data file should also work in the '2d View'. Currently, it only works in the 'Project Tree'.
![qHB5kMafYv](https://user-images.githubusercontent.com/2849257/130331276-5f3fd3d6-3f3d-41b5-ae13-a28a4f39e4b9.png)

**Comment by ericgyounkin** [comment]
I think I looked at this a long time ago, and did not find a great way forward.  I'll take another look though.

**Comment by ericgyounkin** [comment]
Closing this issue.  Resolved in 0.7.6.
