### ISSUE TITLE
UI in linux

### ISSUE THREAD

**Issue by davesteps** [noaa-ocs-hydrography/kluster#78]
Hi, is it possible to run the UI in linux (ubuntu)?

**Comment by ericgyounkin** [comment]
It hasn't been tested, but it should work.  The builds are in Windows, but only because that is what we primarily use.  Would you be able to test?

**Comment by davesteps** [comment]
Hi @ericgyounkin Yes I'd be happy to test it out if you could give me some pointers to get it running, thanks.

**Comment by davesteps** [comment]
Yes I have have got the environment setup, I'm able to import the module in a python console

**Comment by ericgyounkin** [comment]
@davesteps oh, then you should be run kluster as a module from a shell, after you have activated the environment

(pydro38) C:\>python -m HSTB.kluster

**Comment by davesteps** [comment]
Thanks, I'm getting

```
ModuleNotFoundError: No module named 'posixreg'
```

**Comment by ericgyounkin** [comment]
That is a module that should get installed with Kluster.

C:\Pydro21_Dev\envs\kluster_test_disabled\Lib\site-packages\HSTB\shared\posixreg.py

Your path won't be exactly like mine of course, but do you have this file in your site-packages?

**Comment by ericgyounkin** [comment]
@davesteps  I would also try "whereis python" just to ensure that you are using the kluster_test (or whatever you named your new environment) python.  I mention that because that module is automatically installed on pip installing Kluster.

**Comment by davesteps** [comment]
> That is a module that should get installed with Kluster.
> 
> C:\Pydro21_Dev\envs\kluster_test_disabled\Lib\site-packages\HSTB\shared\posixreg.py

Yes the module exists in my site-packages

> I would also try "whereis python" just to ensure that you are using the kluster_test (or whatever you named your new environment) python. I mention that because that module is automatically installed on pip installing Kluster.

Confirmed I am using the correct python:

```
(kluster_test) david@ubuntuv20:~$ which python
/home/david/miniconda3/envs/kluster_test/bin/python
```
I'm wondering if it is a environment variable issue

**Comment by ericgyounkin** [comment]
It could also be some of the path stuff that I use to get QGIS to work.  You could try:

(kluster_test) C:\>python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> from HSTB.shared import posixreg

Just to isolate that one call.

I can also try and spin up a Linux instance via Docker to try and get it all working.

**Comment by davesteps** [comment]
The above (`from HSTB.shared import posixreg` straight into the console) worked. Just appears to be the gui module cannot find the shared module. Here is the full error:

```
(kluster_test) david@ubuntuv20:~$ python -m HSTB.kluster
Traceback (most recent call last):
  File "/home/david/miniconda3/envs/kluster_test/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/david/miniconda3/envs/kluster_test/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/david/miniconda3/envs/kluster_test/lib/python3.8/site-packages/HSTB/kluster/__main__.py", line 7, in <module>
    from HSTB.kluster.gui import kluster_main
  File "/home/david/miniconda3/envs/kluster_test/lib/python3.8/site-packages/HSTB/kluster/gui/kluster_main.py", line 25, in <module>
    from HSTB.kluster.gui import dialog_vesselview, kluster_explorer, kluster_project_tree, kluster_3dview_v2, \
  File "/home/david/miniconda3/envs/kluster_test/lib/python3.8/site-packages/HSTB/kluster/gui/dialog_vesselview.py", line 19, in <module>
    from HSTB.kluster.gui.common_widgets import AcceptDialog
  File "/home/david/miniconda3/envs/kluster_test/lib/python3.8/site-packages/HSTB/kluster/gui/common_widgets.py", line 9, in <module>
    from HSTB.shared import RegistryHelpers
  File "/home/david/miniconda3/envs/kluster_test/lib/python3.8/site-packages/HSTB/shared/RegistryHelpers.py", line 23, in <module>
    from .settings import *
  File "/home/david/miniconda3/envs/kluster_test/lib/python3.8/site-packages/HSTB/shared/settings.py", line 6, in <module>
    from posixreg import *
ModuleNotFoundError: No module named 'posixreg'

```

**Comment by ericgyounkin** [comment]
Hi @davesteps.  OK that's good information.  I'll try and get Docker going tomorrow to test on Ubuntu.

I did notice that you have a path like

../envs/kluster_test/lib/python3.8/site-packages/HSTB/shared\posixreg.py

where mine is like

..\envs\kluster_test\Lib\site-packages\HSTB\shared\posixreg.py

without that python3.8 folder.  Is that the norm for conda in Linux environment?  Are all your site packages in that python3.8 folder?  I wonder if that difference is breaking our codebase somewhere.

**Comment by davesteps** [comment]
> Is that the norm for conda in Linux environment?

Pretty sure that is standard for conda in linux, all the python packages are in there

**Comment by ericgyounkin** [comment]
I've tested Kluster GUI in VirtualBox/Ubuntu 20.04.3 LTS and replicated your issue.  I believe I have resolved this issue in the hstb.shared repository.  Can you try uninstalling/reinstalling hstb.shared?

`(kluster_test) eyou102@eyou102-VirtualBox:/$ pip uninstall hstb.shared`

`(kluster_test) eyou102@eyou102-VirtualBox:/$ pip install git+https://github.com/noaa-ocs-hydrography/shared.git#egg=hstb.shared`

`(kluster_test) eyou102@eyou102-VirtualBox:/$ python -m HSTB.kluster`

That should bring up the GUI.  I've tested with the .all file that is in the Kluster repo, and it works.

**Comment by davesteps** [comment]
Yes can confirm that works for me now. Thanks!

**Comment by ericgyounkin** [comment]
Fantastic!  Thanks for testing!

**Comment by davesteps** [comment]
For reference the recipe I am using to run UI on Ubuntu (20.04.3):

1. Clone repo and cd into it (v0.8.8)
2. `conda env create -f environment.yml`
3. `pip install .`
4. `python -m HSTB.kluster`
