### ISSUE TITLE
Getting an error while processing/georeferenceing .all file

### ISSUE THREAD

**Issue by davesteps** [noaa-ocs-hydrography/kluster#82]
Getting this error when trying to process a .all file. Unlike #79 I can import/convert the file but it is the next processing/georefererencing stage which fails:

```
****Building tx/rx vectors at time of transmit/receive****
Operating on system serial number = 275
using installation params 1616079030
Traceback (most recent call last):
  File "/snap/pycharm-community/267/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/david/kluster/HSTB/kluster/fqpr_convenience.py", line 308, in process_multibeam
    fqpr_inst.get_orientation_vectors(initial_interp=orientation_initial_interpolation, subset_time=subset_time)
  File "/home/david/kluster/HSTB/kluster/fqpr_generation.py", line 2208, in get_orientation_vectors
    self.generate_starter_orientation_vectors(prefixes, timestmp)
  File "/home/david/kluster/HSTB/kluster/fqpr_generation.py", line 623, in generate_starter_orientation_vectors
    rx_heading = abs(float(self.multibeam.xyzrph[txrx[1] + '_h'][tstmp]))
KeyError: 'rx_h'
```

File info:
```
FQPR: Fully Qualified Ping Record built by Kluster Processing
-------------------------------------------------------------
Contains:
2 sonar heads, 18000 pings, version 0.8.9
Start: Thu Mar 18 14:50:30 2021 UTC
End: Thu Mar 18 14:55:30 2021 UTC
Minimum Latitude:  <omitted> Maximum Latitude: <omitted>
Minimum Longitude:  <omitted> Maximum Longitude:  <omitted>
Minimum Northing: Unknown Maximum Northing: Unknown
Minimum Easting: Unknown Maximum Easting: Unknown
Minimum Depth: Unknown Maximum Depth: Unknown
Current Status: converted complete
Sonar Model Number: em2040_dual_rx
Primary/Secondary System Serial Number: 275/281
Horizontal Datum: 32630
Vertical Datum: waterline
Navigation Source: Unknown
Contains SBETs: False
Sound Velocity Profiles: 1
```

**Comment by davesteps** [comment]
Inspecting the `self.multibeam.xyzrph` dict there are `rx_port_h` and `rx_stbd_h` instead of rx_h:

```
...
SortedDict({'1616079030': 0.001}), 'rx_port_h': SortedDict({'1616079030': 180.33}), 'rx_port_p': 
({'1616079030': -1.91}), 'rx_port_r': SortedDict({'1616079030': -35.165}), 'rx_port_x': ({'1616079030': 0.003}), 
'rx_port_y': SortedDict({'1616079030': -0.336}), 'rx_port_z': SortedDict({'1616079030': -0.162}), 'rx_stbd_h': 
({'1616079030': 182.38}), 'rx_stbd_p': SortedDict({'1616079030': -0.28}), 'rx_stbd_r': ({'1616079030': 33.525}),
 'rx_stbd_x': SortedDict({'1616079030': -0.01}), 'rx_stbd_y': SortedDict({'1616079030': 0.338}), 'rx_stbd_z': 
...
```

**Comment by ericgyounkin** [comment]
OK, I see the issue here.  I'll need to update xarray_conversion.return_xyz_prefixes_for_system.  If my code is working correctly, you have a sonar with a single transmitter, dual receivers.  So the `self.multibeam.xyzrph` dict has a `tx_h `and `rx_port_h` `rx_stbd_h`?

This should be a simple fix i can put in the next release.  I'll go through the conversion code to see if there are any other instances where this configuration will be an issue.

**Comment by davesteps** [comment]
> So the `self.multibeam.xyzrph` dict has a `tx_h `and `rx_port_h` `rx_stbd_h`?

Yes that appears to be the case. I have managed to get it 'working' by changing `return_xyz_prefixes_for_systems` to the following ( to be honest though I don't know if this is appropriate or whether something else needs modifying):

```
if 'tx_r' in self.xyzrph and 'rx_r' in self.xyzrph:
    leverarms = [['tx', 'rx']]
elif 'tx_port_r' in self.xyzrph and 'rx_port_r' in self.xyzrph:
    leverarms = [['tx_port', 'rx_port'], ['tx_stbd', 'rx_stbd']]
elif 'tx_r' in self.xyzrph and 'rx_port_r' in self.xyzrph:
    leverarms = [['tx', 'rx_port'], ['tx', 'rx_stbd']]
else:
    self.logger.error('Not supporting this sonartype yet.')
    raise NotImplementedError('Not supporting this sonartype yet.')
```

**Comment by ericgyounkin** [comment]
@davesteps Thanks!  This is logic that will be in Kluster 0.8.10.  Technically there is also a dual tx, single rx configuration that is possible from the system's perspective, although I don't think in practice that would make sense?  I might put it in there anyway just as a placeholder and print a warning.

I had to make a few other tweaks that had this incorrect assumption built in, still going through the rest of the code.

https://github.com/noaa-ocs-hydrography/kluster/commits/kluster_0_8_10

**Comment by ericgyounkin** [comment]
@davesteps is this issue resolved in the latest version?  Please let me know if I can close.

**Comment by davesteps** [comment]
Hi @ericgyounkin, I have run that survey again with `v0.9.0` and it appears to give a slightly different error now. I'll close this a open a new issue.
