### ISSUE TITLE
Unexpected filter behaviour?

### ISSUE THREAD

**Issue by davesteps** [noaa-ocs-hydrography/kluster#90]
Hi @ericgyounkin ,

I have noticed some unexpected behaviour when using the filter plugin functionality. It has to do with when running in 'Points View' mode and when we have data selected over multiple lines. Our filter tool works by creating 3d 'chips' of data, you would expect that a larger area results in more chips however as you see from the example below when I select similar sized subsets I can very different numbers of chips when the subset spans multiple lines:

Subset of single line - results in 12 chips in our filter
![image](https://user-images.githubusercontent.com/5738970/160630148-00982b0d-72e8-46a9-a95f-269549cc65d3.png)

Similar sized subset crossing 2 lines - 195 chips for our model!
![image](https://user-images.githubusercontent.com/5738970/160631121-fb0f99b7-3403-4e1e-b199-b1c29d1b3628.png)

I continue to try and debug but was wondering if you had any insights on why this could be happening?

Many thanks.

**Comment by ericgyounkin** [comment]
Hi @davesteps

Hard to say for certain, but I suspect what is happening is that you are seeing the current limitation with filtering by subset, where it has to process all pings that intersect with the region.  So the first square you probably just had a few pings from the outerbeams of one line, and the second square probably had a number of pings from both lines.  

It has to include all pings that are partially in the square to preserve the rectangular array structure (ping, beam) that allows you to use the FQPR object in the filter plugin.  I could return (x, y, z, beam) 1d arrays instead, but that limits you.  

So if you have just one beam from a ping in the box, you'll need to process the whole ping.  Not sure that there is a solution that doesn't limit the current plugin functionality.  Does that make sense?

**Comment by ericgyounkin** [comment]
Yeah, that doesn't sound right.  Maybe there is an issue with the subset that I am doing there.  Let me go back and take a look.

**Comment by ericgyounkin** [comment]
@davesteps Just to let you know, I can reproduce this issue, not sure what the solution is just yet, I'll keep you informed.

**Comment by ericgyounkin** [comment]
@davesteps OK it was actually pretty simple.  I was one off in the split indices, kind of embarrassing.  Gotta add one to np.where() when you use the return for np.split().  

See the commit to subset.py below.

Also, I removed the old requirement to have converted data selected in the project view when you filter the points view data.

You can switch to the dev branch to get the changes, or wait for 0.9.1 to release, might be a week or so.

https://github.com/noaa-ocs-hydrography/kluster/commit/7c9dc3687a5311f2c9d41205036bb813c637985c

**Comment by davesteps** [comment]
Many thanks @ericgyounkin will check out the branch

**Comment by davesteps** [comment]
Can confirm that is working now, awesome work thanks @ericgyounkin. As is typical just when you fix one bug another becomes apparent :) there is something going on with redrawing the points after filtering. I'll open a separate issue. Happy to close this one. Thanks again.
